from pathlib import Path
import json
from ares_print_analyzer.preprocessing import add_markers_to_stl
from datetime import datetime, timezone



"""
This preprocessing file prepares a user selected STL for slicing and prepares 
a configuration file for use in the computer vision and image generation pipeline.

User supplied inputs:
    1. The path to an STL file, list of STL files, or a folder containing multiple STL files.
    2. The output directory for the procesed files. Processed 3d files will be saved in a 
        sub-folder of this directory with the model name. The configuation JSON will be to the parent directory
    3. A camera calibration file, generated by the included jupyter notebook
        If you want to use your own camera calibration file, it must include
        the openCV camera matrix, disortion coeffs. and whether the fisheye
        camera model was used.
    4. An approximate color for the printer filament as an RGB tuple (R,G,B).
    5. An approximate color for the print bed as an RGB tuple (R,G,B).
        * Note: To get these values, we suggest using the camera to manualy take 
        an image of the bed with a sample of filament on it and using a color picker 
        tool to get RGB values

User Configurable Settings:
    * Note all sizes are in whatever unit the STL is in. Usually this is mm, but could also be m, so use caution.
    1. marker_size: The size (diameter or side length) of the computer vision markers 
    2. padding: Additional padding to use for placing markers. The center of the marker will be placed at 
                The original model bounding box location + the padding amount.
    3. marker_thickness: The z thickness of the marker. Should be thick enough to provide an opaque marker but still 
                        thin, as thick markers could interfere with the computer vision pose estimation. 
    4. recenter: Many STLs do not have the centers of the bounding box located at (0, 0). This option will recenter the model and export a new version
                 If this option is used, it is important to s
"""

# %% User Inputs
# Path to the STL can be a path or list of paths
source_stl = "/Users/artsloan/Dropbox/Documents/Code/research/ARES/ATHENA/athena-demo-resources/stl files/orignal/string_test.stl"
# Output path for 3D models
output_dir = "/Users/artsloan/Dropbox/Documents/Code/research/ARES/ATHENA/athena-demo-resources/processed files"

# Camera calibration JSON
camera_json = "/Users/artsloan/Dropbox/Documents/Code/research/ARES/ATHENA/ARES-Print-Analyzer/resources/camera_calibration.json"
# Filament Color
filament_rgb = (245,211,122)
# Bed Color
bed_rgb = (60,50,60)

# %% User Configuration
# Switch this to True to use config values below
use_config= False
# Marker Size (default: 8.0)
marker_size = 8.0
# Bounding Box Padding (default: 8.0)
padding = 8.0
# Marker Z thickness (default: 0.4)
marker_thickness = 0.4
# Set the start value of the ARUCO markers (default: 1)
marker_start = 1
# 


# %% Logic
files_to_process = []
if isinstance(source_stl,str):
    p = Path(source_stl)
    if p.is_file(): # Single STL file
        files_to_process.append(p)
    if p.is_dir(): # Folder of STL files
        file_list = p.glob('*.stl')
elif isinstance(source_stl,list):
    for f in source_stl:
        files_to_process.append(Path(f))

output_dir = Path(output_dir)
camera_json = Path(camera_json)

# Make the configuation JSON
with open(camera_json, 'r') as f:
    json_data = json.load(f)

json_data['created_on'] = datetime.now(timezone.utc).isoformat()
json_data['filament_color_rgb'] = filament_rgb
json_data['bed_color_rgb'] = bed_rgb

output_dir.mkdir(parents=True,exist_ok=True)
config_file = output_dir/ "config.json"
with open(str(config_file), 'w') as f:
    json.dump(json_data, f)  
# Process the STL(s)
for f in files_to_process:
    # Modify STL files and save to output dir
    if use_config:
        add_markers_to_stl(f, output_dir,
                           padding=padding,
                           marker_size=marker_size,
                           marker_thickness=marker_thickness,
                           marker_start=marker_start)
    else:
        add_markers_to_stl(f,output_dir)


